locals {
  eks_cluster_name = "NAME"

  # At this moment, there is no way to discover these
  # automatically.
  eks_autoscaling_groups = [
    "eks-UUID-1",
    "eks-UUID-2",
  ]

  # Region where security groups will reside
  target_region = "eu-central-1"
  # VPC where security groups will reside
  vpc_id = "VPC_ID"
  # Node ports that Ambassador instances are bound to
  ports = [31080, 31443]
  # Prefix that lambda generated security groups will have
  security_group_prefix = "AUTOGENERATED"


  ip_change_topic = "arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged"
}
